# file: .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 } # or 10; match your local
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm run -s lint || true
      - run: pnpm run -s build
